class Settings:
    DEFAULT_DOWNLOAD_DIRECTORY = 'music'
    ARTIST_IMAGES_SUB_DIR = '_Artists'
    PLAYLIST_METADATA_SUB_DIR = '_Playlists'
    GLOBALS_SAVE_FILE = '_downloaded_store.json'
    FULL_DOWNLOAD_RECURISVE_LIMIT = 0x4000
    FULL_DOWNLOAD_THREAD_LIMIT = 50
    VERBOSE_OUTPUTS = False
    AUTO_DOWNLOAD_PLAYLIST_METADATA = True
